apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebsupgrade
  namespace: openebs-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openebsupgrade
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebsupgrade
subjects:
- kind: ServiceAccount
  name: openebsupgrade
  namespace: openebs-test
roleRef:
  kind: ClusterRole
  name: openebsupgrade
  apiGroup: rbac.authorization.k8s.io
---
