apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebsoperator
  namespace: openebs-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openebsoperator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - openebses
  - deployments
  - replicasets
  - jobs
  - cronjobs
  - statefulsets
  - daemonsets
  - configmaps
  - secrets
  - services
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - "*"
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - "*"
  resources:
  - nodes
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebsoperator
subjects:
- kind: ServiceAccount
  name: openebsoperator
  namespace: openebs-test
roleRef:
  kind: ClusterRole
  name: openebsoperator
  apiGroup: rbac.authorization.k8s.io
---
